baseURL = 'https://thatisdrtruman.github.io/'
languageCode = 'en-us'
title = "Joseph Liu's Portfolio and Blog"
theme = "ananke"
publishDir = "public"

[author]
name = "Joe Liu"
email = "joeliu3rd@icloud.com"

[outputs]
  home = ["HTML", "RSS"]

[[menu.main]]
    name = "About Me"
    identifier = "about"
    url = "/posts/i-am-joe-liu/"

[[menu.main]]
    name = "Writing (WIP)"
    identifier = "writings"
    url = "/categories/writings/"

[[menu.main]]
    name = "Tech Dev"
    identifier = "techdev"
    url = "/categories/app/"

[[menu.main]]
    name = "Podcast"
    identifier = "podcast"
    url = "/categories/podcast/"

[[menu.main]]
    name = "Game Dev/Designs"
    identifier = "game"
    url = "/categories/games/"

[[menu.main]]
    name = "Music/Sound"
    identifier = "sound"
    url = "/categories/music/"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  site_logo = "img/lj-left-logo-white.svg"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/people/LJ-Left-Creations-by-Joe-Liu/61555492546128/"
label = "My Facebook Enterprise Page: LJ-Left Creations by Joe Liu"

[[params.ananke_socials]]
name = "tiktok"
url = "https://www.tiktok.com/@ljleft_creations"
label = "My TikTok International account"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/ljleftcreationsbyjoeliu/"
label = "Instagram Business Account"

[[params.ananke_socials]]
name = "youtube"
url = "https://youtube.com/@LJ-LeftCreations"
label = "My Business Youtube account"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/joseph-liu-9b022b1b0/"
label = "LinkedIn"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/thatisdrtruman/"
label = "My Github"

[[params.ananke_socials]]
name = "rss"
url = "https://thatisdrtruman.github.io/index.xml"
label = "My RSS, useful if you want to have updates about me"

[[menu.main]]
    name = "Contact Me"
    identifier = "Contact Me"
    url = "/contact-me/"