baseURL = 'https://thatisdrtruman.github.io/'
languageCode = 'en-us'
title = 'Joseph Liu'
theme = "ananke"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  site_logo = "img/lj-left-logo-white.svg"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/joseph-liu-9b022b1b0/"
label = "My Linkedin"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/joseph.liu.7161953"
label = "My Facebook"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/thatisdrtruman/"
label = "My Insta"

[[params.ananke_socials]]
name = "tiktok"
url = "https://www.tiktok.com/@thatisdrtruman"
label = "My tiktok international account"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/thatisdrtruman/"
label = "My github"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/liuj40149012"
label = "My X or Twitter"

[[params.ananke_socials]]
name = "youtube"
url = ""
label = "Youtube account (Coming Soon)"
